### ISSUE TITLE
404 Error when fetching latest rstudio

### ISSUE THREAD

**Issue by paulkitt** [Oefenweb/ansible-rstudio#15]
When fetching the latest rstudio version `rstudio_version: '2023.12.1-402'` the url set via `rstudio_download_url` from vars is not correct anymore.

Moving the  `rstudio_download_url` var to defaults whould be great

**Comment by tersmitten** [comment]
Which OS / Version are you using?

**Comment by paulkitt** [comment]
We are deploying the role to Ubuntu 22.04

**Comment by tersmitten** [comment]
Fixed in #17
