### ISSUE TITLE
WARNING in download deb task

### ISSUE THREAD

**Issue by thiagogomesverissimo** [Oefenweb/ansible-rstudio#5]
```
 [WARNING]: Consider using the get_url or uri module rather than running curl.  If you need to use command because
get_url or uri is insufficient you can add warn=False to this command task or set command_warnings=False in ansible.cfg
to get rid of this message.

```

**Comment by tersmitten** [comment]
We use `curl` because `get_url` (with `python < 2.7.9`) has issues with `SNI`

**Comment by tersmitten** [comment]
https://github.com/ansible/ansible-modules-core/issues/1716#issuecomment-120995697

**Comment by thiagogomesverissimo** [comment]
We can set warn: no? can I send a PR?

**Comment by tersmitten** [comment]
Does that also work for `ansible-lint`?

**Comment by tersmitten** [comment]
Fixed in https://github.com/Oefenweb/ansible-rstudio/commit/514520be89257a59282519351488b57b7e2f2d86
